### PR TITLE
Add docker-compose file and update README documentation

### PR DESCRIPTION
**Pull request by aescanes**
Hallo, Wie geht's?

Thank you for all your effort in running the site and providing valuable information for all of us.
The docker-compose file will make life easier for future users and collaborators on this project.

### CODE REVIEW

**Comment by nicbou** [comment]
Hi there! Thanks for the pull request.

Does a docker-compose file make sense in this situation? Usually docker-compose is used to compose a system out of multiple containers. For example, All About Berlin has a docker-compose file that includes this image. A docker-compose file for a single container does not really make sense in this case, I think.

**Comment by aescanes** [comment]
Hi Nicbou, no problem. I liked your initiative on all this "mess" that is German bureaucracy. 
I agree with you that a docker-compose file makes more sense when you have multiple services and images that are going to work together, but also this can be a simplification for the user. In this case as you saw in the README file the user can run a simple command and that will do all the magic.

`docker-compose run --rm appointments appointments --q`

This will:
- Create the image and install all the dependencies
- Run the command to start the _appointments_ process
- Remove the container after the process is done (cleaning)

**Comment by aescanes** [comment]
> Hi Nicbou, no problem. I liked your initiative on all this "mess" that is German bureaucracy. I agree with you that a docker-compose file makes more sense when you have multiple services and images that are going to work together, but also this can be a simplification for the user. In this case as you saw in the README file the user can run a simple command and that will do all the magic.
> 
> `docker-compose run --rm appointments appointments --q`
> 
> This will:
> 
> * Create the image and install all the dependencies
> * Create the container and run the command to start the _appointments_ process
> * Remove the container after the process is done (cleaning)

What do you think Nicbou? Tchüss

**Comment by nicbou** [comment]
I'll stand by my original point: this adds more code, but it does not really add more convenience over running a single docker image directly. This should be something that docker users already understand how to do, and it's out of scope for this project.

Nonetheless, thanks a lot for taking the time to create and argue for this pull request. I hope that this does not discourage you to contribute more patches.

**Pull request closed without merging**
